apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-2
  annotations:
    argocd-image-updater.argoproj.io/write-back-method: argocd
    argocd-image-updater.argoproj.io/image-list: "enhanced-devops=masrafdevxokacar.azurecr.io/enhanced-devops:latest"
    argocd-image-updater.argoproj.io/enhanced-devops.update-strategy: latest
spec:
  project: default
  source:
    repoURL: https://github.com/xokacar/argocd-2
    path: ./argocd-2-chart
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  destination: 
    server: 'https://kubernetes.default.svc'
    namespace: argocd
