apiVersion: argoproj.io/v1alphav1
kind: Application
metadata:
  name: argocd-2
spec:
  project: default
  source:
    repoURL: https://github.com/xokacar/argocd-2
    path: ./argocd-2-chart
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  destination: 
    server: 'https://kubernetes.default.svc'
    namespace: argocd
